import type { Metadata } from 'next'
import { Inter, Liu_Jian_Mao_Cao } from 'next/font/google'
import Link from 'next/link'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Personal Blog Post',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className='flex py-3 shadow font-bold text-gray-800 bg-slate-300'>
          <Link href="/" className='px-6 '>Home</Link>
          <Link href="/blogs" className='px-6'>Blogs</Link>
          <Link href="/about" className='px-6'>About</Link>
          <div className='mx-auto'/>
          <Link href="/profile" className='px-6'>Profile</Link>
        </nav>
        <div className='px-6 py-3'>
          {children}
        </div>
      </body>
    </html>
  )
}
